### ISSUE TITLE
[Android Bootcamp] Project 0: Todo - Ready for Review

### ISSUE THREAD

**Issue by mysgithub** [mysgithub/ToDoApp#1]
My app is complete, please review. @codepathreview  @codepath 

Also, should I complete optional features mentioned? 
Another question is video tutorial ToDo app did not crashed even when first time launch in case of "todo.txt" does not exists; rather my ToDo app did; I expected the same as object being access without initializing; what could be the reason ToDo app did not crashed?

**Comment by nidhi1608** [comment]
What was the exact error message? Can you elaborate?

**Comment by mysgithub** [comment]
In my code "onCreate" method if I don't initialize **todoItems** then following line generates this exception -
"lvItems.setAdapter(todoAdapter);" 

Exception:
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.codepath.todoapp/com.codepath.todoapp.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
....
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
            at android.widget.ArrayAdapter.getCount(ArrayAdapter.java:337)
            at android.widget.ListView.setAdapter(ListView.java:491)
            at com.codepath.todoapp.MainActivity.onCreate(MainActivity.java:38)

**Comment by nidhi1608** [comment]
Good catch. Thats a small oversight on our part. The instructor may have had an existing "todo.txt" file from the video prep work. A more sophisticated way is to initialize `todoItems` in the catch block [here](https://github.com/mysgithub/ToDoApp/blob/master/app/src/main/java/com/codepath/todoapp/MainActivity.java#L74-L77).

**Comment by nidhi1608** [comment]
Also, feel free to work on all optionals as and when you get a chance. There are some very important concepts to learns there so I would highly encourage you to work on all of the optionals.

**Comment by nidhi1608** [comment]
Our prework tool is unable to match you with an application for some reason. Can you please let me know your full name and the company you represent so I can manually look up your application?

**Comment by mysgithub** [comment]
Sorry for that! Actually your prework tool might not able link my account as I have changed github username; after I realize that I changed back to same again; but might have created problem in your prework tool.
Following is my information:
Name: Ghanshyam Rokde
Company: Visa Inc.
Let me know if you need anything else!

**Comment by mysgithub** [comment]
To fix that exception I have initialized before populating todo list @line 34 in my program [here](https://github.com/mysgithub/ToDoApp/blob/master/app/src/main/java/com/codepath/todoapp/MainActivity.java#L34).
Thanks for the review, I will start on all optional features assignment and will get back to you soon.

**Comment by nidhi1608** [comment]
The fix looks good. Thanks Ghanshyam!

**Comment by mysgithub** [comment]
New features are added please review!!

Thanks!

**Comment by nesquena** [comment]
Hi Ghanshyam,

Sorry for long delay in communication, are you still interested in participating in the February Android class?

Looks good, nice to see you completed many optionals already. This exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project.

The next step is to continue working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and to **schedule a short 10 minute phone conversation** with us. Navigate to [today's date and onward from there](https://calendar.google.com/calendar/selfsched?sstoken=UURvT01vbzBza1pnfGRlZmF1bHR8NzVjYzBkN2EyZTRiOGRmYjZlZjhmMjA2N2IyMGMwYWU) and choose a 15-minute slot. Let us know if none of those times work.

Once you select a slot, can you make sure to **include best number** to reach you at to the invite? Look forward to chatting soon!

**Comment by mysgithub** [comment]
Thanks Nathan,
I am very much interested in Android class. Sure I will setup time to chat with you and I will share interest of learning Android Development.
